package com.test.service.groups;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.gId
     *
     * @mbg.generated
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.gName
     *
     * @mbg.generated
     */
    private String gname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.gId
     *
     * @return the value of groups.gId
     *
     * @mbg.generated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.gId
     *
     * @param gid the value for groups.gId
     *
     * @mbg.generated
     */
    public void setGid(String gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.gName
     *
     * @return the value of groups.gName
     *
     * @mbg.generated
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.gName
     *
     * @param gname the value for groups.gName
     *
     * @mbg.generated
     */
    public void setGname(String gname) {
        this.gname = gname;
    }
}